CREATE INDEX X_RXNCONSO_STR ON rxnorm_prescribe.RXNCONSO(STR);
CREATE INDEX X_RXNCONSO_RXCUI ON rxnorm_prescribe.RXNCONSO(RXCUI);
CREATE INDEX X_RXNCONSO_TTY ON rxnorm_prescribe.RXNCONSO(TTY);
CREATE INDEX X_RXNCONSO_CODE ON rxnorm_prescribe.RXNCONSO(CODE);

CREATE INDEX X_RXNSAT_RXCUI ON rxnorm_prescribe.RXNSAT(RXCUI);
CREATE INDEX X_RXNSAT_ATV ON rxnorm_prescribe.RXNSAT(ATV);
CREATE INDEX X_RXNSAT_ATN ON rxnorm_prescribe.RXNSAT(ATN);

CREATE INDEX X_RXNREL_RXCUI1 ON rxnorm_prescribe.RXNREL(RXCUI1);
CREATE INDEX X_RXNREL_RXCUI2 ON rxnorm_prescribe.RXNREL(RXCUI2);
CREATE INDEX X_RXNREL_RELA ON rxnorm_prescribe.RXNREL(RELA);