CREATE INDEX X_RXNCONSO_STR ON rxnorm.RXNCONSO(STR);
CREATE INDEX X_RXNCONSO_RXCUI ON rxnorm.RXNCONSO(RXCUI);
CREATE INDEX X_RXNCONSO_TTY ON rxnorm.RXNCONSO(TTY);
CREATE INDEX X_RXNCONSO_CODE ON rxnorm.RXNCONSO(CODE);

CREATE INDEX X_RXNSAT_RXCUI ON rxnorm.RXNSAT(RXCUI);
CREATE INDEX X_RXNSAT_ATV ON rxnorm.RXNSAT(ATV);
CREATE INDEX X_RXNSAT_ATN ON rxnorm.RXNSAT(ATN);

CREATE INDEX X_RXNREL_RXCUI1 ON rxnorm.RXNREL(RXCUI1);
CREATE INDEX X_RXNREL_RXCUI2 ON rxnorm.RXNREL(RXCUI2);
CREATE INDEX X_RXNREL_RELA ON rxnorm.RXNREL(RELA);

CREATE INDEX X_RXNATOMARCHIVE_RXAUI ON rxnorm.RXNATOMARCHIVE(RXAUI);
CREATE INDEX X_RXNATOMARCHIVE_RXCUI ON rxnorm.RXNATOMARCHIVE(RXCUI);
CREATE INDEX X_RXNATOMARCHIVE_MERGED_TO ON rxnorm.RXNATOMARCHIVE(MERGED_TO_RXCUI);

